### ISSUE TITLE
unintended automatic release to maven central

### ISSUE THREAD

**Issue by nqzero** [jinahya/ossrh-parent#2]
this pom causes the deploy goal to release to maven central, which was not obvious to me

my feeling is the pom should be modified to disable automatic release

if not, the readme should make it more clear that "deploy" will release to maven central. i don't know if people discover poms directly thru search.maven.org and then use them directly without checking the github repo. if not, this may be sufficient

**Comment by nqzero** [comment]
my argument was convincing enough that sonatype were willing to delete my unintentionally released artifact (which they generally don't do)

https://issues.sonatype.org/browse/MVNCENTRAL-1504

**Comment by jinahya** [comment]
@nqzero The sole purpose of this pom is deploying artifacts to the OSSRH repository. And the main purpose of the OSSRH (releases) repository is for synchronizing to the Central.

**Comment by nqzero** [comment]
i've been doing a lot of deploy-drop cycles to make sure things validate etc. and you can run tests (though i haven't gotten to that point yet). no idea how common these non-release activities are in general

i'm not expert by any means - i saw the name "ossrh" and figured it was safe to play with

maybe just change the readme to say "Now you can release the artifact to maven central as follows:"

regardless, definitely a very nice pom - makes working with ossrh painless

**Comment by jinahya** [comment]
I added some caveats on the readme. I hope that's what you wanted it be.  Oh.... on `develop` branch...

**Comment by nqzero** [comment]
ah - the situation is more complicated than i understood. i haven't figured out how to use snapshot releases yet

but yes, that looks like a good addition to the readme
